import { describe, expect, it } from "vitest";
import { isGeneratedWorkbookName } from "./cachePolicy";

describe("isGeneratedWorkbookName", () => {
  it("targets only workbooks generated by this app", () => {
    expect(
      isGeneratedWorkbookName("MPESA_Statement_2026-06-23_to_2026-07-23.xlsx"),
    ).toBe(true);
    expect(isGeneratedWorkbookName("personal-budget.xlsx")).toBe(false);
    expect(isGeneratedWorkbookName("MPESA_Statement_notes.pdf")).toBe(false);
  });
});
